// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

export type AddObject = {
  objectId: bigint,
  worldId: string,
  channelId: string,
  assetId: bigint,
  positionX: number,
  positionY: number,
  positionZ: number,
  rotationQuaternionX: number,
  scaleX: number,
  animState: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace AddObject {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("objectId", AlgebraicType.createU64Type()),
      new ProductTypeElement("worldId", AlgebraicType.createStringType()),
      new ProductTypeElement("channelId", AlgebraicType.createStringType()),
      new ProductTypeElement("assetId", AlgebraicType.createU64Type()),
      new ProductTypeElement("positionX", AlgebraicType.createF32Type()),
      new ProductTypeElement("positionY", AlgebraicType.createF32Type()),
      new ProductTypeElement("positionZ", AlgebraicType.createF32Type()),
      new ProductTypeElement("rotationQuaternionX", AlgebraicType.createF32Type()),
      new ProductTypeElement("scaleX", AlgebraicType.createF32Type()),
      new ProductTypeElement("animState", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: AddObject): void {
    AddObject.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): AddObject {
    return AddObject.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

